spring.application.name=medistock
server.port=8080

spring.mongodb.uri=${MONGODB_URI}

spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=America/Sao_Paulo

logging.level.org.springframework.data.mongodb.core=INFO