spring.application.name=stockline
server.port=8080
spring.data.mongodb.uri=mongodb://admin:admin123@localhost:27017/stockline?authSource=admin

spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=America/Sao_Paulo
logging.level.org.springframework.data.mongodb.core=INFO